/* Starter designs shipped with the app. They are plain specs, so duplicating one just copies the spec. */
import {normalizeSpec} from './flats.js';
const S=(id,name,category,description,spec,tags=[])=>({id:'starter:'+id,name,category,description,spec:normalizeSpec(spec),tags,source:'starter'});
export const CATEGORIES=[['all','All'],['tops','Tops'],['dresses','Dresses'],['skirts','Skirts'],['trousers','Trousers'],['jackets','Jackets'],['traditional','Traditional']];
export const STARTERS=[
 S('crew-tee','Everyday crew-neck tee','tops','A relaxed T-shirt with a round neck and short set-in sleeves.',{family:'top',fit:'regular',neckline:'round',sleeve:'short',length:'hip'},['basic','knit']),
 S('cropped-puff','Cropped puff-sleeve top','tops','A short fitted top with a square neck and gathered puff sleeves.',{family:'top',fit:'fitted',neckline:'square',sleeve:'short',sleeveStyle:'puff',length:'crop'},['party','feminine']),
 S('peplum-blouse','Peplum blouse with tie','tops','A fitted blouse with a V-neck, elbow sleeves and a flared peplum hem.',{family:'top',fit:'fitted',neckline:'v',sleeve:'elbow',length:'waist',hem:'peplum',closure:'tie'},['office','flared']),
 S('shirt-classic','Classic button shirt','tops','A collared shirt with a front placket, long sleeves, cuffs and a curved hem.',{family:'top',fit:'regular',neckline:'collar',sleeve:'long',length:'hip',closure:'buttons',hem:'curved',details:['cuffs'],pockets:'patch'},['shirt','office']),
 S('boat-tunic','Boat-neck tunic','tops','A loose tunic with a wide boat neck and three-quarter sleeves.',{family:'top',fit:'boxy',neckline:'boat',sleeve:'three-quarter',length:'tunic'},['relaxed']),
 S('shift-dress','Sleeveless shift dress','dresses','A straight, easy dress with a scoop neck and darts.',{family:'dress',fit:'regular',neckline:'scoop',sleeve:'none',length:'knee',waist:'none',skirt:'straight',details:['darts']},['workwear']),
 S('wrap-midi','Wrap midi dress','dresses','A wrap front dress with a V-neck, elbow sleeves and a tie waist.',{family:'dress',fit:'fitted',neckline:'v',sleeve:'elbow',length:'midi',waist:'belt',skirt:'wrap',closure:'wrap'},['wrap','event']),
 S('aline-dress','A-line day dress','dresses','A fitted bodice with a round neck and a skirt that flares gently from the waist.',{family:'dress',fit:'fitted',neckline:'round',sleeve:'short',length:'knee',waist:'seam',skirt:'a-line'},['classic']),
 S('empire-gown','Empire-line gown','dresses','A sweetheart bodice with a high waist and a long flowing skirt.',{family:'dress',fit:'fitted',neckline:'sweetheart',sleeve:'none',length:'maxi',waist:'empire',skirt:'flared'},['gown','event']),
 S('tiered-maxi','Tiered maxi dress','dresses','A loose maxi dress with a square neck, bell sleeves and gathered tiers.',{family:'dress',fit:'regular',neckline:'square',sleeve:'elbow',sleeveStyle:'bell',length:'maxi',waist:'seam',skirt:'tiered'},['boho']),
 S('pencil-skirt','High-waist pencil skirt','skirts','A close-fitting skirt with a waistband, back slit and zip.',{family:'skirt',fit:'fitted',skirt:'pencil',length:'knee',waist:'seam',closure:'zip',details:['slit']},['office']),
 S('circle-skirt','Circle skirt','skirts','A full skirt with a smooth waistband and a wide swinging hem.',{family:'skirt',fit:'regular',skirt:'circle',length:'midi',waist:'seam'},['full']),
 S('gathered-skirt','Gathered skirt with pockets','skirts','A gathered skirt on an elastic waist with patch pockets.',{family:'skirt',fit:'regular',skirt:'gathered',length:'midi',waist:'elastic',pockets:'patch'},['easy']),
 S('wide-trouser','Wide-leg trousers','trousers','High-waisted trousers with a fly, pleats and a wide leg.',{family:'trousers',fit:'regular',leg:'wide',length:'full',waist:'seam',closure:'zip',details:['pleats'],pockets:'welt'},['tailored']),
 S('tapered-chino','Tapered chinos','trousers','Smart trousers with a fly, belt loops and a tapered leg.',{family:'trousers',fit:'regular',leg:'tapered',length:'ankle',waist:'belt',closure:'buttons',pockets:'welt',details:['belt-loops']},['smart']),
 S('bermuda','Tailored shorts','trousers','Knee-length shorts with cuffs and patch pockets.',{family:'trousers',fit:'regular',leg:'straight',length:'shorts',waist:'belt',pockets:'patch',details:['cuffs','belt-loops']},['summer']),
 S('blazer','Notch-lapel blazer','jackets','A single-breasted blazer with lapels, long sleeves and welt pockets.',{family:'top',fit:'regular',neckline:'lapel',sleeve:'long',length:'tunic',closure:'buttons',pockets:'welt',details:['yoke']},['tailored']),
 S('bomber','Zip bomber jacket','jackets','A short boxy jacket with a stand collar, zip front and ribbed hem.',{family:'top',fit:'boxy',neckline:'stand',sleeve:'long',sleeveStyle:'raglan',length:'waist',closure:'zip',hem:'bands',details:['cuffs'],pockets:'welt'},['street']),
 S('hoodie','Zip hoodie','jackets','A hooded jacket with a zip front, kangaroo pocket and ribbed cuffs.',{family:'top',fit:'oversized',neckline:'hood',sleeve:'long',sleeveStyle:'drop',length:'hip',closure:'zip',pockets:'kangaroo',hem:'bands',details:['cuffs']},['casual']),
 S('kaftan','Embroidered kaftan','traditional','A long loose kaftan with an embroidered neck panel and side slits.',{family:'dress',fit:'oversized',neckline:'round',sleeve:'elbow',length:'maxi',waist:'none',skirt:'straight',details:['embroidery','slit']},['kaftan','african']),
 S('bubu','Bell-sleeve bubu gown','traditional','A flowing gown with a wide boat neck, bell sleeves and an embroidered front.',{family:'dress',fit:'boxy',neckline:'boat',sleeve:'long',sleeveStyle:'bell',length:'maxi',waist:'none',skirt:'a-line',details:['embroidery']},['bubu','african']),
 S('jumpsuit','Belted jumpsuit','dresses','A utility jumpsuit with a collar, short sleeves, wide legs and a belt.',{family:'jumpsuit',fit:'regular',neckline:'collar',sleeve:'short',leg:'wide',length:'full',waist:'belt',closure:'buttons',pockets:'patch'},['utility'])
];
