import React,{useMemo,useState} from 'react';
import {Bot,Send,User,Sparkles,RefreshCw} from 'lucide-react';
import {api} from '../api.js';

export default function Assistant(){
 const [messages,setMessages]=useState([{role:'assistant',text:'Hi — I’m your FabricNow workspace assistant. I can help you manage products, garment extraction, production, collections, marketing, assets and store workflows.'}]);
 const [input,setInput]=useState('');const [busy,setBusy]=useState(false);
 const send=async e=>{e?.preventDefault();const message=input.trim();if(!message||busy)return;const history=messages.slice(-10);setInput('');setMessages(m=>[...m,{role:'user',text:message}]);setBusy(true);try{const d=await api('/api/assistant/workspace',{method:'POST',body:JSON.stringify({message,history})});setMessages(m=>[...m,{role:'assistant',text:d.reply||'I could not generate a response.'}])}catch(err){setMessages(m=>[...m,{role:'assistant',text:err.message||'The assistant is temporarily unavailable.'}])}finally{setBusy(false)}};
 const quick=['How many products need review?','What should I finish before publishing this product?','Help me build a collection from my approved products','What assets are missing from my latest products?'];
 return <div className="assistant-page"><section className="assistant-shell"><div className="assistant-head"><div><div className="eyebrow">FABRICNOW AI</div><h2>Workspace Assistant</h2><p>Gemini-powered help grounded in your workspace data and production workflow.</p></div><button className="btn btn-ghost" onClick={()=>setMessages([{role:'assistant',text:'Conversation cleared. What would you like to work on?'}])}><RefreshCw size={15}/> New chat</button></div><div className="assistant-body"><div className="assistant-quick">{quick.map(q=><button key={q} onClick={()=>setInput(q)}>{q}</button>)}</div><div className="assistant-messages">{messages.map((m,i)=><div key={i} className={`assistant-msg ${m.role}`}><div className="assistant-avatar">{m.role==='assistant'?<Bot size={16}/>:<User size={16}/>}</div><div className="assistant-bubble">{m.text}</div></div>)}{busy&&<div className="assistant-msg assistant"><div className="assistant-avatar"><Bot size={16}/></div><div className="assistant-bubble assistant-thinking"><Sparkles size={15}/> Gemini is thinking…</div></div>}</div></div><form className="assistant-compose" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about your workspace…" disabled={busy}/><button className="btn btn-primary" disabled={busy||!input.trim()}>{busy?<span className="spin">◌</span>:<Send size={16}/>}<span className="hide-sm">Send</span></button></form></section></div>
}
