import React,{useState} from 'react';
import {Bot,Send,User,Sparkles,RefreshCw,Command,Layers3,Shirt,Factory,BookOpen,ArrowRight} from 'lucide-react';
import {api} from '../api.js';

export default function Assistant(){
 const [messages,setMessages]=useState([{role:'assistant',text:'Welcome to FabricNow AI. I can help you understand your live workspace, prepare product workflows and find what needs attention.'}]);
 const [input,setInput]=useState(''); const [busy,setBusy]=useState(false);
 const send=async e=>{e?.preventDefault();const message=input.trim();if(!message||busy)return;const history=messages.slice(-10);setInput('');setMessages(m=>[...m,{role:'user',text:message}]);setBusy(true);try{const d=await api('/api/assistant/workspace',{method:'POST',body:JSON.stringify({message,history})});setMessages(m=>[...m,{role:'assistant',text:d.reply||'I could not generate a response.'}])}catch(err){setMessages(m=>[...m,{role:'assistant',text:err.message||'The assistant is temporarily unavailable.'}])}finally{setBusy(false)}};
 const quick=[['Workspace','What needs my attention right now?',Command],['Products','How many products need review?',Shirt],['Production','What is missing before I publish?',Factory],['Collections','Help me build a collection from approved products',BookOpen]];
 return <div className="assistant-page"><section className="assistant-hero"><div><span className="pm-eyebrow">FABRICNOW AI · WORKSPACE COPILOT</span><h2>Ask your workspace. Get useful next actions.</h2><p>AI assistance grounded in the live FabricNow workspace instead of generic chat.</p></div><button className="btn btn-ghost" onClick={()=>setMessages([{role:'assistant',text:'New workspace conversation started. What are you working on?'}])}><RefreshCw size={15}/> New chat</button></section><div className="assistant-layout"><aside className="assistant-context"><div className="assistant-context-head"><span>START WITH A TASK</span><Sparkles size={15}/></div>{quick.map(([a,q,I])=><button key={q} onClick={()=>setInput(q)}><span><I size={17}/></span><div><strong>{a}</strong><small>{q}</small></div><ArrowRight size={14}/></button>)}<div className="assistant-grounding"><Layers3 size={17}/><div><strong>Workspace grounded</strong><small>Responses can use your connected product, asset, production and collection records.</small></div></div></aside><section className="assistant-shell"><div className="assistant-chat-head"><div className="assistant-avatar large"><Bot size={20}/></div><div><strong>FabricNow AI</strong><span>Workspace assistant · Live context</span></div><span className="assistant-live"><i/> Connected</span></div><div className="assistant-messages">{messages.map((m,i)=><div key={i} className={`assistant-msg ${m.role}`}><div className="assistant-avatar">{m.role==='assistant'?<Bot size={16}/>:<User size={16}/>}</div><div><div className="assistant-bubble">{m.text}</div><small className="assistant-time">{m.role==='assistant'?'FabricNow AI':'You'}</small></div></div>)}{busy&&<div className="assistant-msg assistant"><div className="assistant-avatar"><Bot size={16}/></div><div className="assistant-bubble assistant-thinking"><Sparkles size={15}/> Thinking from workspace context…</div></div>}</div><form className="assistant-compose" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about products, assets, production or marketing…" disabled={busy}/><button className="btn btn-primary" disabled={busy||!input.trim()}>{busy?'Working…':<><Send size={16}/> Send</>}</button></form></section></div></div>
}
