import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Bookmark, ExternalLink, Image as ImageIcon, Link2, RefreshCw, Search, ShieldCheck, Sparkles } from 'lucide-react';
import { api } from '../api.js';
import { Skeleton, Spinner } from '../components/ui.jsx';


function Card({pin,onSave,onStudio,saved}){
  const image=pin.imageUrl || pin.mediaUrl;
  return <article className="pin-card">
    <div className="pin-image-wrap">{image?<img src={image} alt={pin.title||pin.altText||'Pinterest inspiration'} loading="lazy"/>:<div className="pin-image-empty"><ImageIcon size={28}/></div>}</div>
    <div className="pin-card-body">
      <div className="pin-card-title">{pin.title||pin.description||'Pinterest inspiration'}</div>
      <div className="pin-source"><span>Pinterest</span>{pin.boardOwner?.username?` · @${pin.boardOwner.username}`:''}</div>
      <div className="pin-actions">
        <button className="btn btn-primary btn-sm" onClick={()=>onStudio(pin)}><Sparkles size={14}/> Pattern Studio</button>
        <button className="btn btn-ghost btn-sm" onClick={()=>onSave(pin)}>{saved?<Bookmark size={14} fill="currentColor"/>:<Bookmark size={14}/>} {saved?'Saved':'Save'}</button>
        {pin.link&&<a className="btn btn-ghost btn-sm" href={pin.link} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Source</a>}
      </div>
      {pin.link&&<button className="source-copy" onClick={()=>navigator.clipboard?.writeText(pin.link)}><Link2 size={12}/> Copy source link</button>}
    </div>
  </article>
}

export default function PinterestResearch({setPage,libraryOnly=false}){
  const [query,setQuery]=useState(''); const [submitted,setSubmitted]=useState(''); const [items,setItems]=useState([]); const [saved,setSaved]=useState([]); const [loading,setLoading]=useState(false); const [libraryLoading,setLibraryLoading]=useState(libraryOnly); const [error,setError]=useState(''); const [configured,setConfigured]=useState(null);
  useEffect(()=>{ let alive=true; setLibraryLoading(true); api('/api/companies/inspirations').then(d=>{if(!alive)return; const rows=(d.inspirations||[]).map(x=>({id:x.externalId||x.id,title:x.title,description:x.description,imageUrl:x.imageUrl,link:x.sourceUrl,source:'Pinterest'}));setSaved(rows);}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLibraryLoading(false)}); return ()=>{alive=false}; },[]);
  const search=async(e)=>{e?.preventDefault(); const q=query.trim(); if(!q)return; setSubmitted(q);setLoading(true);setError('');try{const d=await api(`/api/companies/pinterest/search?q=${encodeURIComponent(q)}`);setItems(d.items||[]);setConfigured(d.configured!==false);if(!d.configured&&d.searchUrl)setError('Pinterest is not connected for this company yet. Connect it in Apps & Integrations to search inside FabricNow.');}catch(e){setError(e.message)}finally{setLoading(false)}};
  const toggleSave=async(pin)=>{const exists=saved.some(x=>x.id===pin.id);if(exists){return;}try{await api('/api/companies/inspirations',{method:'POST',body:JSON.stringify({provider:'pinterest',externalId:pin.id,title:pin.title,description:pin.description,imageUrl:pin.imageUrl,sourceUrl:pin.link,sourceAccount:pin.boardOwner?.username||'',metadata:{altText:pin.altText||''}})});}catch(e){setError(e.message);return;} const next=[pin,...saved.filter(x=>x.id!==pin.id)];setSaved(next)};
  const sendToStudio=(pin)=>{try{localStorage.setItem('fabricnow.patternReference',JSON.stringify({id:pin.id,title:pin.title||'',imageUrl:pin.imageUrl||'',sourceUrl:pin.link||'',provider:'Pinterest'}));}catch{} setPage('studio');};
  const shown=libraryOnly?saved:items;
  return <div className="pm-page pinterest-page">
    <div className="pm-head"><div><div className="pm-eyebrow">INSPIRATION · VISUAL RESEARCH</div><h2>{libraryOnly?'Inspiration Library':'Pinterest Research'}</h2><p>{libraryOnly?'Approved visual references shared by this company for quick handoff into Pattern Studio.':'Search Pinterest inspiration, keep the source link, and send a reference into Pattern Studio.'}</p></div><div className="pm-actions"><a className="btn btn-ghost" href="https://www.pinterest.com/" target="_blank" rel="noreferrer"><ExternalLink size={15}/> Open Pinterest</a>{!libraryOnly&&<button className="btn btn-ghost" onClick={()=>{setQuery(submitted);search()}} disabled={!submitted||loading}><RefreshCw size={15}/> Refresh</button>}</div></div>
    {!libraryOnly&&<>
      <div className="pinterest-search-hero"><div className="pinterest-brand-lockup"><span className="pinterest-p" aria-hidden="true">P</span><div><strong>Search visual ideas</strong><span>Use garment, fabric, silhouette or collection terms.</span></div></div><form onSubmit={search} className="pinterest-search-form"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. indigo batik maxi dress, linen co-ord, Ankara sleeve"/><button className="btn btn-primary" disabled={loading}>{loading?<Spinner size={15}/>:<>Search</>}</button></form><div className="pinterest-safety"><ShieldCheck size={15}/><span>FabricNow keeps the source URL. Only use imagery you have permission to use in production.</span></div></div>
      {error&&<div className="error pinterest-error">{error}<button className="btn btn-ghost btn-sm" onClick={()=>setPage('integrations')}>Open Apps & Integrations</button></div>}
      {submitted&&configured&&<div className="pinterest-result-head"><div><strong>{items.length} references</strong><span> for “{submitted}”</span></div><span>Save a reference or send it to Pattern Studio.</span></div>}
    </>}
    {!libraryOnly&&loading&&<div className="pin-grid pin-grid-skeleton">{Array.from({length:6}).map((_,i)=><div className="pin-card pin-skeleton-card" key={i}><Skeleton height={220} radius={14}/><div className="pin-skeleton-copy"><Skeleton width="58%" height={13}/><Skeleton width="82%" height={10}/></div></div>)}</div>}
    {!libraryOnly&& !items.length && !loading&&<div className="inspiration-empty"><div className="inspiration-empty-icon"><Search size={22}/></div><div className="inspiration-empty-copy"><span>VISUAL RESEARCH</span><h3>{submitted?'No references found':'Search for your next design reference'}</h3><p>{submitted?`No Pinterest references were returned for “${submitted}”. Try a broader garment, fabric, silhouette or collection term.`:'Search by garment, fabric, silhouette, print or collection mood. Results can be saved to your company Inspiration Library or sent directly to Pattern Studio.'}</p><div className="empty-query-chips"><button type="button" onClick={()=>setQuery('linen summer dress')}>linen summer dress</button><button type="button" onClick={()=>setQuery('Ankara sleeve')}>Ankara sleeve</button><button type="button" onClick={()=>setQuery('indigo batik')}>indigo batik</button></div></div><button className="btn btn-primary inspiration-empty-cta" onClick={()=>document.querySelector('.pinterest-search-form input')?.focus()}>Start searching <ArrowRight size={15}/></button></div>}
    {libraryOnly&&libraryLoading?<div className="inspiration-library-skeleton"><Skeleton width="35%" height={20}/><Skeleton width="68%" height={12}/><Skeleton width="92%" height={12}/><div className="pin-grid">{Array.from({length:4}).map((_,i)=><div className="pin-card pin-skeleton-card" key={i}><Skeleton height={230} radius={14}/><div className="pin-skeleton-copy"><Skeleton width="62%" height={13}/><Skeleton width="84%" height={10}/></div></div>)}</div></div>:libraryOnly&&!shown.length?<div className="lib-empty"><div className="lib-empty-tiles" aria-hidden="true">{[0,1,2,3,4].map(i=><div className="lib-empty-tile" key={i}><ImageIcon size={22}/></div>)}</div><div className="lib-empty-body"><div className="inspiration-empty-icon"><Bookmark size={22}/></div><span className="lib-empty-label">INSPIRATION LIBRARY</span><h3>Your saved references will appear here</h3><p>Save useful Pinterest references for your company so authorized designers can return to them and hand them into Pattern Studio.</p><button className="btn btn-primary" onClick={()=>setPage('pinterest-research')}>Research on Pinterest <ArrowRight size={15}/></button><ol className="lib-empty-steps"><li><b>1</b><span>Search Pinterest for garments, fabrics or moods</span></li><li><b>2</b><span>Save the references your team approves</span></li><li><b>3</b><span>Send any of them into Pattern Studio</span></li></ol></div></div>:<div className="pin-grid">{shown.map(pin=><Card key={pin.id} pin={pin} saved={saved.some(x=>x.id===pin.id)} onSave={toggleSave} onStudio={sendToStudio}/>)}</div>}
    {!libraryOnly&&<div className="pinterest-footnote"><Link2 size={14}/><span>Source links are preserved so your team can return to the original Pinterest content.</span></div>}
  </div>
}
