import React,{useMemo,useState} from 'react';
import {Search,Plus,Sparkles,Download,CheckCircle2,Clock3,AlertTriangle,Shirt, Ruler, FileText, Kanban, ShieldCheck, Layers3, Image, Upload, Filter, MoreHorizontal, ArrowRight, Database, Palette, Tag, PackageCheck, X, ChevronRight} from 'lucide-react';

const garments=[
 {id:'GN-1042',name:'Kente Evening Dress',type:'Dress',fabric:'Kente',status:'Review',confidence:94,updated:'Today'},
 {id:'GN-1041',name:'Ankara Peplum Set',type:'Two-piece',fabric:'Ankara',status:'Approved',confidence:98,updated:'Yesterday'},
 {id:'GN-1038',name:'Batik Relaxed Kaftan',type:'Kaftan',fabric:'Batik',status:'Production',confidence:91,updated:'Sep 30'},
 {id:'GN-1034',name:'Aso-Ebi Draped Gown',type:'Gown',fabric:'Lace',status:'Draft',confidence:87,updated:'Sep 29'},
];
const fabrics=[['Kente','Woven','Ghana','18'],['Ankara','Wax print','West Africa','26'],['Batik','Resist dye','Ghana','11'],['Adire','Indigo dye','Nigeria','9'],['Lace','Embroidered','Imported','14'],['Adinkra','Symbol print','Ghana','7']];
const measures=['Bust','Waist','Hip','Shoulder','Armhole','Sleeve length','Garment length','Neck','Rise','Inseam'];
function Badge({children,tone='neutral'}){return <span className={`pm-badge ${tone}`}>{children}</span>}
function Shell({eyebrow,title,description,actions,children}){return <div className="pm-page"><div className="pm-head"><div><div className="pm-eyebrow">{eyebrow}</div><h2>{title}</h2><p>{description}</p></div><div className="pm-actions">{actions}</div></div>{children}</div>}
function Metric({label,value,detail,icon:Icon}){return <div className="pm-metric"><span className="pm-metric-icon"><Icon size={17}/></span><div><small>{label}</small><strong>{value}</strong><span>{detail}</span></div></div>}

export function GarmentLibrary({setPage}){const [q,setQ]=useState('');const [filter,setFilter]=useState('All');const list=useMemo(()=>garments.filter(g=>(filter==='All'||g.status===filter)&&`${g.name} ${g.type} ${g.fabric}`.toLowerCase().includes(q.toLowerCase())),[q,filter]);return <Shell eyebrow="DESIGN · GARMENT INTELLIGENCE" title="Garment Library" description="Your structured source of truth for every garment, extraction, pattern and production record." actions={<><button className="btn btn-ghost"><Filter size={15}/> Filters</button><button className="btn btn-primary" onClick={()=>setPage('fashion-capture')}><Plus size={15}/> Add garment</button></>}>
 <div className="pm-metrics"><Metric label="Garments" value="1,248" detail="+86 this month" icon={Shirt}/><Metric label="AI analyzed" value="1,102" detail="88% coverage" icon={Sparkles}/><Metric label="Needs review" value="37" detail="12 high priority" icon={AlertTriangle}/><Metric label="Approved" value="842" detail="Ready for production" icon={CheckCircle2}/></div>
 <div className="pm-toolbar"><div className="pm-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search garments, fabrics, styles..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Draft</option><option>Review</option><option>Approved</option><option>Production</option></select></div>
 <div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>Garment</th><th>Type</th><th>Fabric</th><th>AI confidence</th><th>Status</th><th>Updated</th><th/></tr></thead><tbody>{list.map(g=><tr key={g.id}><td><div className="pm-primary"><span className="pm-thumb"><Shirt size={18}/></span><span><strong>{g.name}</strong><small>{g.id}</small></span></div></td><td>{g.type}</td><td><span className="fabric-chip"><span/>{g.fabric}</span></td><td><div className="confidence"><i style={{width:`${g.confidence}%`}}/><b>{g.confidence}%</b></div></td><td><Badge tone={g.status==='Approved'?'success':g.status==='Review'?'warning':g.status==='Production'?'info':'neutral'}>{g.status}</Badge></td><td>{g.updated}</td><td><button className="icon-action"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div>
 <div className="pm-bottom-card"><div><Sparkles size={20}/><div><strong>AI garment intake</strong><p>Upload one or more photos and automatically create a structured garment record, detected pieces and confidence notes.</p></div></div><button className="btn btn-ghost" onClick={()=>setPage('fashion-capture')}>Open Product Capture <ArrowRight size={15}/></button></div>
 </Shell>}

export function FabricLibrary(){const [selected,setSelected]=useState('Kente');return <Shell eyebrow="MATERIALS · FABRIC INTELLIGENCE" title="Fabric Library" description="Build a reusable catalog of African fabrics, prints, repeats, colours and production notes." actions={<button className="btn btn-primary"><Plus size={15}/> Add fabric</button>}>
 <div className="pm-layout-2"><section><div className="fabric-grid">{fabrics.map(([name,type,origin,count])=><button key={name} className={`fabric-card ${selected===name?'selected':''}`} onClick={()=>setSelected(name)}><div className="fabric-pattern"><span/></div><div><strong>{name}</strong><small>{type} · {origin}</small></div><b>{count} assets</b></button>)}</div></section><section className="pm-panel fabric-detail"><div className="fabric-detail-art"><div className="fabric-pattern large"><span/></div></div><div className="pm-eyebrow">SELECTED MATERIAL</div><h3>{selected}</h3><p>Structured material record with repeat information, colourways, source and production guidance.</p><div className="detail-grid"><div><small>Category</small><strong>Woven print</strong></div><div><small>Origin</small><strong>Ghana</strong></div><div><small>Repeat</small><strong>48 × 48 cm</strong></div><div><small>Weight</small><strong>Medium</strong></div></div><button className="btn btn-primary"><Database size={15}/> Edit material record</button></section></div>
 <div className="pm-panel"><div className="pm-panel-head"><div><h3>Fabric intelligence</h3><p>Standardize material data so AI and production teams use the same vocabulary.</p></div><Badge tone="success">AI ready</Badge></div><div className="tag-row"><span><Tag size={14}/> Print repeat</span><span><Palette size={14}/> Colourways</span><span><Shirt size={14}/> Garment compatibility</span><span><PackageCheck size={14}/> Care & handling</span></div></div>
 </Shell>}

export function MeasurementStudio(){const [size,setSize]=useState('M');const [values,setValues]=useState(Object.fromEntries(measures.map((m,i)=>[m,[92,76,100,39,44,61,108,37,30,79][i]])));return <Shell eyebrow="PRODUCTION · FIT SYSTEM" title="Measurements & Size Profiles" description="Create reusable size charts and generate garment measurements consistently across products." actions={<button className="btn btn-primary"><Plus size={15}/> New size profile</button>}>
 <div className="pm-size-tabs">{['XS','S','M','L','XL','XXL','Custom'].map(x=><button className={size===x?'active':''} onClick={()=>setSize(x)} key={x}>{x}</button>)}</div>
 <div className="pm-layout-2"><section className="pm-panel"><div className="pm-panel-head"><div><h3>{size} base measurements</h3><p>Centimetres · editable before pattern generation</p></div><Badge tone="info">Base size</Badge></div><div className="measurement-grid">{measures.map(m=><label key={m}><span>{m}</span><div><input type="number" value={values[m]} onChange={e=>setValues({...values,[m]:e.target.value})}/><small>cm</small></div></label>)}</div><div className="pm-form-actions"><button className="btn btn-ghost">Reset</button><button className="btn btn-primary"><CheckCircle2 size={15}/> Save profile</button></div></section><section className="pm-panel"><div className="pm-panel-head"><div><h3>Size grading</h3><p>How the base size scales across your range.</p></div></div>{['Bust','Waist','Hip','Length'].map((x,i)=><div className="grade-row" key={x}><span>{x}</span><b>{[4,4,4,2][i]} cm</b><div className="grade-bar"><i style={{width:`${[78,64,86,42][i]}%`}}/></div></div>)}<div className="fit-note"><Ruler size={17}/><div><strong>Fit profile</strong><p>Balanced African fit · moderate ease · production ready.</p></div></div></section></div>
 </Shell>}

export function TechPacks(){const [active,setActive]=useState('Kente Evening Dress');const sections=['Overview','Measurements','Construction','Bill of materials','Labelling','Packaging'];return <Shell eyebrow="PRODUCTION · TECHNICAL DOCUMENTS" title="Tech Pack Builder" description="Turn approved garments into complete production-ready technical packages." actions={<><button className="btn btn-ghost"><Upload size={15}/> Import</button><button className="btn btn-primary"><Download size={15}/> Export PDF</button></>}>
 <div className="pm-tech-layout"><aside className="pm-panel pm-tech-sidebar"><div className="pm-eyebrow">PRODUCT</div><h3>{active}</h3><Badge tone="success">Approved</Badge>{sections.map((x,i)=><button className={i===0?'active':''} key={x}>{x}<ChevronRight size={15}/></button>)}<button className="btn btn-primary full"><Sparkles size={15}/> AI complete pack</button></aside><main className="pm-panel tech-preview"><div className="tech-top"><div><span className="pm-eyebrow">TECHNICAL SPECIFICATION · FN-1042</span><h3>{active}</h3><p>Version 1.4 · Updated today · Approved by Design Team</p></div><Badge tone="success">Production ready</Badge></div><div className="tech-visual"><div className="tech-garment"><Shirt size={82}/><span>FRONT</span></div><div className="tech-garment"><Shirt size={82}/><span>BACK</span></div><div className="tech-spec"><strong>Construction notes</strong><p>Princess seam bodice, concealed back zip, lined skirt, reinforced shoulder seam.</p><strong>Fabric</strong><p>Kente woven print · medium weight · directional repeat.</p><strong>Seam allowance</strong><p>1 cm standard · 1.5 cm side seams.</p></div></div><div className="tech-table"><div><span>Component</span><b>Qty</b><b>Supplier note</b></div>{['Main fabric','Lining','Invisible zipper','Interfacing','Care label','Brand label'].map((x,i)=><div key={x}><span>{x}</span><b>{i<2?'1.8 m':'1 pc'}</b><small>{i<2?'Approved material':'Standard trim'}</small></div>)}</div></main></div>
 </Shell>}

export function ProductionBoard(){const columns=[['Design',garments.slice(3,4)],['AI Review',garments.slice(0,1)],['Approved',garments.slice(1,2)],['Production',garments.slice(2,3)],['Completed',[]]];return <Shell eyebrow="PRODUCTION · WORKFLOW" title="Production Board" description="Move every garment through a controlled pipeline from design approval to production completion." actions={<button className="btn btn-primary"><Plus size={15}/> Add work item</button>}>
 <div className="board-summary"><Metric label="On track" value="82%" detail="17 of 21 products" icon={CheckCircle2}/><Metric label="In review" value="7" detail="2 overdue" icon={Clock3}/><Metric label="Blocked" value="2" detail="Requires action" icon={AlertTriangle}/></div><div className="kanban">{columns.map(([title,items])=><section className="kanban-col" key={title}><div className="kanban-head"><strong>{title}</strong><span>{items.length}</span></div>{items.map(g=><article className="kanban-card" key={g.id}><div className="kanban-art"><Shirt size={25}/></div><div><strong>{g.name}</strong><small>{g.fabric} · {g.id}</small></div><div className="kanban-foot"><Badge tone={title==='Approved'?'success':title==='AI Review'?'warning':'neutral'}>{title==='AI Review'?'Needs review':'On track'}</Badge><button className="icon-action"><MoreHorizontal size={16}/></button></div></article>)}{!items.length&&<div className="kanban-empty"><Kanban size={18}/><span>Drop products here</span></div>}<button className="add-card"><Plus size={14}/> Add product</button></section>)}</div>
 </Shell>}

export function QualityControl(){const [checked,setChecked]=useState(false);return <Shell eyebrow="AI QUALITY · HUMAN REVIEW" title="AI Quality Control" description="Catch extraction, symmetry, fabric and pattern issues before a garment reaches production." actions={<button className="btn btn-primary"><ShieldCheck size={15}/> Run new audit</button>}>
 <div className="pm-metrics"><Metric label="Audited" value="486" detail="This month" icon={ShieldCheck}/><Metric label="Passed" value="451" detail="92.8% pass rate" icon={CheckCircle2}/><Metric label="Review queue" value="23" detail="6 critical" icon={AlertTriangle}/><Metric label="Avg confidence" value="94.2%" detail="+2.1% vs last month" icon={Sparkles}/></div>
 <div className="pm-layout-2"><section className="pm-panel"><div className="pm-panel-head"><div><h3>Kente Evening Dress</h3><p>Automated garment audit · FN-1042</p></div><Badge tone="warning">Needs review</Badge></div><div className="audit-score"><div className="score-ring"><strong>94</strong><span>/100</span></div><div><h3>High confidence</h3><p>Most garment pieces were detected reliably. Two items need a human decision before production.</p></div></div>{[['Garment piece detection',98,'Passed'],['Symmetry & alignment',96,'Passed'],['Fabric segmentation',92,'Passed'],['Sleeve construction',84,'Review'],['Occluded back detail',71,'Review']].map(([x,v,s])=><div className="audit-row" key={x}><span>{x}</span><div className="audit-progress"><i style={{width:`${v}%`}}/></div><b>{v}%</b><Badge tone={s==='Passed'?'success':'warning'}>{s}</Badge></div>)}<label className="review-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>I reviewed the flagged items and approve this garment for production.</span></label><button className="btn btn-primary" disabled={!checked}><CheckCircle2 size={15}/> Approve quality review</button></section><section className="pm-panel"><div className="pm-panel-head"><div><h3>Detected pieces</h3><p>What the AI found in the source image.</p></div></div><div className="piece-list">{['Front bodice','Back bodice','Sleeve · left','Sleeve · right','Skirt front','Skirt back','Waistband','Invisible zipper'].map((x,i)=><div key={x}><span className="piece-icon"><Layers3 size={15}/></span><strong>{x}</strong><small>{i<6?'Detected':'Inferred'}</small><CheckCircle2 size={15}/></div>)}</div><div className="pm-note"><AlertTriangle size={16}/><span><strong>Human attention</strong><br/>Back detail is partially occluded in the source photo. Confirm construction before exporting the tech pack.</span></div></section></div>
 </Shell>}

export function Integrations(){return <Shell eyebrow="DEVELOPERS · CONNECTED WORKFLOWS" title="Integrations & API" description="Connect FabricNow to commerce, storage, production and internal systems." actions={<button className="btn btn-primary"><Plus size={15}/> Add integration</button>}><div className="integration-cards">{[['Shopify','Publish approved products and inventory feeds.'],['WooCommerce','Sync product content and images.'],['Google Drive','Archive technical documents and assets.'],['Dropbox','Keep production exports synchronized.'],['Webhooks','Send garment and job events to your backend.'],['REST API','Build your own fashion production workflow.']].map(([name,desc],i)=><article className="integration-big" key={name}><div className="integration-big-icon"><Database size={20}/></div><div><h3>{name}</h3><p>{desc}</p><Badge tone={i<2?'success':'neutral'}>{i<2?'Connected':'Available'}</Badge></div><button className="btn btn-ghost">{i<2?'Manage':'Connect'} <ArrowRight size={14}/></button></article>)}</div></Shell>}
