import React,{useEffect,useState} from 'react';
import {ArrowRight,Database,FileText,FolderOpen,Images,Layers3,Plus,Shirt,Sparkles,ShieldCheck,Ruler,Kanban,Palette,RefreshCw,Plug,Zap,Trash2,CheckCircle2,X,Info,Check} from 'lucide-react';
import {api} from '../api.js';
import {PanelSkeleton, Spinner} from '../components/ui.jsx';

function Shell({eyebrow,title,description,actions,children}){return <div className="pm-page"><div className="pm-head"><div><div className="pm-eyebrow">{eyebrow}</div><h2>{title}</h2><p>{description}</p></div><div className="pm-actions">{actions}</div></div>{children}</div>}
function EmptyState({icon:Icon=FolderOpen,label='READY WHEN YOU ARE',title,body,primary,onPrimary}){return <div className="library-empty fashion-module-empty"><div className="empty-state-icon"><Icon size={23}/></div><div className="library-empty-copy"><span className="library-empty-label">{label}</span><h4>{title}</h4><p>{body}</p>{primary&&<div className="library-empty-actions"><button className="btn btn-primary" onClick={onPrimary}>{primary}<ArrowRight size={15}/></button></div>}<div className="empty-state-foot"><Info size={13}/><span>Your company data will appear here once the first record is created.</span></div></div></div>}
function Notice({error,ok}){if(!error&&!ok)return null;return <div className={error?'error':'success-panel'} role="status">{error||ok}</div>}
function FormModal({title,children,onClose,onSave,busy}){const meta={ 'Add fabric':['MATERIALS','Add a material record to your company library.'],'New size profile':['FIT SYSTEM','Define reusable measurements and size standards.'],'Create tech pack':['TECHNICAL DOCUMENT','Build a production package linked to a garment.'],'Add production work':['PRODUCTION WORKFLOW','Create a tracked production item for your team.'],'Run quality audit':['QUALITY CONTROL','Queue a product for review and record the decision.']};const [kicker,desc]=meta[title]||['FASHION OS','Complete the details below.'];return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="module-modal" role="dialog" aria-modal="true" aria-label={title}><header className="module-modal-head"><div><span className="module-modal-kicker">{kicker}</span><h3>{title}</h3><p>{desc}</p></div><button className="module-modal-close" type="button" onClick={onClose} aria-label="Close"><X size={18}/></button></header><div className="module-modal-body">{children}</div><footer className="module-modal-foot"><span><ShieldCheck size={14}/> Saved to this company workspace</span><div className="module-actions"><button className="btn btn-ghost" type="button" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={onSave}>{busy?<Spinner size={15}/>:<><Check size={15}/> Save</>}</button></div></footer></div></div>}
function useResource(path,key){const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=()=>{setLoading(true);api(path).then(d=>setItems(d[key]||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);return {items,setItems,loading,error,reload:load};}

export { GarmentLibrary, FabricLibrary, MeasurementStudio, TechPacks, ProductionBoard, QualityControl } from './ModulePages.jsx';

const appLogos={
  pinterest:'https://cdn.simpleicons.org/pinterest/E60023',
  instagram:'https://cdn.simpleicons.org/instagram/E4405F',
  tiktok:'https://cdn.simpleicons.org/tiktok/111111',
  shopify:'https://cdn.simpleicons.org/shopify/96BF48',
  woocommerce:'https://cdn.simpleicons.org/woocommerce/96588A',
  canva:'https://cdn.simpleicons.org/canva/00C4CC',
  'google-drive':'https://cdn.simpleicons.org/googledrive/4285F4',
  dropbox:'https://cdn.simpleicons.org/dropbox/0061FF'
};
function AppLogo({id,name}){const src=appLogos[id];return src?<img className="integration-brand-logo" src={src} alt={`${name} logo`} loading="lazy"/>:<span className="integration-brand-fallback">{id==='custom-api'?'API':'WH'}</span>;}
export function Integrations(){const [apps,setApps]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=()=>{setLoading(true);api('/api/companies/apps').then(d=>setApps(d.apps||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);const connect=async(app)=>{try{const d=await api(`/api/companies/integrations/${app.id}/connect`,{method:'POST',body:JSON.stringify({accountName:`${app.name} company connection`})});if(d.authorizeUrl){window.location.href=d.authorizeUrl;return;}load()}catch(e){setError(e.message)}};const disconnect=async(app)=>{try{await api(`/api/companies/integrations/${app.id}`,{method:'DELETE'});load()}catch(e){setError(e.message)}};return <Shell eyebrow="APPS · CONNECTED WORKFLOWS" title="Integrations & API" description="Connect company-level applications. A connection is shared only with users who have access to this company and the required integration permission." actions={<button className="btn btn-ghost" onClick={load}><RefreshCw size={15}/> Refresh</button>}><Notice error={error}/>{loading?<div className="app-grid"><div className="app-card app-card-skeleton"><div className="ui-skeleton app-logo-skeleton"/><div className="ui-skeleton" style={{width:'46%',height:16}}/><div className="ui-skeleton" style={{width:'84%',height:10}}/><div className="ui-skeleton" style={{width:'34%',height:38,borderRadius:8}}/></div><div className="app-card app-card-skeleton"><div className="ui-skeleton app-logo-skeleton"/><div className="ui-skeleton" style={{width:'52%',height:16}}/><div className="ui-skeleton" style={{width:'78%',height:10}}/><div className="ui-skeleton" style={{width:'34%',height:38,borderRadius:8}}/></div></div>:<div className="app-grid">{apps.map(app=>{const connected=app.integration?.status==='connected';return <div className={`app-card ${connected?'connected':''}`} key={app.id}><div className="app-card-head"><div className="app-icon"><AppLogo id={app.id} name={app.name}/></div><div><h4>{app.name}</h4><span className="app-status">{connected?'● Connected':'○ Not connected'}</span></div></div><p>{app.description}</p><div className="module-actions"><button className="btn btn-primary" onClick={()=>connected?disconnect(app):connect(app)}>{connected?'Disconnect':'Connect'}</button>{connected&&<span className="tag ok"><Zap size={11}/> Company-wide</span>}</div></div>})}</div>}</Shell>}
