import React,{useEffect,useMemo,useRef,useState} from 'react';
import {api,API,downloadFile} from '../api.js';
import {useToast} from '../toast.jsx';
import {Bot, Check, ChevronDown, Circle, Download, Eraser, Hand, Layers3, Minus, Move, Plus, Ruler, Save, Scissors, Sparkles, Square, Trash2, Wand2} from 'lucide-react';
import './tailor-tools.css';

const TOOLS=[['select','Select',Hand],['piece','Pattern piece',Square],['seam','Seam',Minus],['dart','Dart',ChevronDown],['notch','Notch',Circle],['grainline','Grainline',Move],['stitch','Stitch',Scissors],['measure','Measure',Ruler],['annotation','Note',Layers3]];
const DEFAULT_OPS=[{id:'piece-1',type:'piece',name:'Front Bodice',x:18,y:20,w:48,h:62,points:[[18,20],[60,20],[66,30],[62,78],[18,82]],cut:2},{id:'piece-2',type:'piece',name:'Back Bodice',x:78,y:20,w:48,h:62,points:[[78,20],[120,20],[126,30],[122,78],[78,82]],cut:1}];

function uid(){return `${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function Board({ops,tool,onChange,selected,setSelected}){
 const svg=useRef(null),[drag,setDrag]=useState(null);
 const point=e=>{const r=svg.current.getBoundingClientRect();return {x:clamp((e.clientX-r.left)/r.width*140,0,140),y:clamp((e.clientY-r.top)/r.height*180,0,180)}};
 const down=e=>{if(tool==='select'){return} const p=point(e); if(tool==='measure'||tool==='seam'||tool==='stitch'||tool==='grainline'){setDrag({start:p,current:p});return} if(tool==='notch'){onChange([...ops,{id:uid(),type:'notch',x:p.x,y:p.y}]);return} if(tool==='annotation'){const text=window.prompt('Note text');if(text)onChange([...ops,{id:uid(),type:'annotation',x:p.x,y:p.y,text:text.slice(0,120)}]);return} if(tool==='dart'){onChange([...ops,{id:uid(),type:'dart',x:p.x,y:p.y,x2:p.x+8,y2:p.y+10}]);return}};
 const move=e=>{if(!drag)return;setDrag({...drag,current:point(e)})};
 const up=()=>{if(!drag)return;const a=drag.start,b=drag.current;const type=tool; if(Math.hypot(b.x-a.x,b.y-a.y)>2)onChange([...ops,{id:uid(),type,x1:a.x,y1:a.y,x2:b.x,y2:b.y,allowance:type==='seam'?1:0}]);setDrag(null)};
 const remove=id=>onChange(ops.filter(o=>o.id!==id));
 return <div className="tt-board-wrap"><svg ref={svg} viewBox="0 0 140 180" className="tt-board" onMouseDown={down} onMouseMove={move} onMouseUp={up} onMouseLeave={up} role="application" aria-label="Tailor pattern board">
  <defs><pattern id="grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M 5 0 L 0 0 0 5" fill="none" stroke="currentColor" strokeOpacity=".08" strokeWidth=".18"/></pattern></defs><rect width="140" height="180" fill="url(#grid)"/>
  {ops.map(o=>o.type==='piece'?<g key={o.id} onClick={()=>setSelected(o.id)} className={selected===o.id?'tt-selected':''}><polygon points={o.points.map(p=>p.join(',')).join(' ')} fill="rgba(92,58,236,.07)" stroke="currentColor" strokeWidth=".8"/><text x={o.x+o.w/2} y={o.y+o.h/2} textAnchor="middle" fontSize="3" fill="currentColor">{o.name}</text><text x={o.x+o.w/2} y={o.y+o.h/2+5} textAnchor="middle" fontSize="2.4" fill="currentColor">Cut {o.cut||1}</text></g>:o.type==='notch'?<circle key={o.id} cx={o.x} cy={o.y} r="1.5" fill="white" stroke="currentColor" strokeWidth=".7"/>:o.type==='dart'?<path key={o.id} d={`M ${o.x} ${o.y} L ${o.x2} ${o.y2} M ${o.x} ${o.y} L ${o.x-5} ${o.y2}`} fill="none" stroke="currentColor" strokeWidth=".7"/>:o.type==='annotation'?<text key={o.id} x={o.x} y={o.y} fontSize="3" fill="currentColor">{o.text}</text>:o.type==='grainline'?<line key={o.id} x1={o.x1} y1={o.y1} x2={o.x2} y2={o.y2} stroke="currentColor" strokeWidth=".55" markerEnd="url(#arrow)"/>:<line key={o.id} x1={o.x1} y1={o.y1} x2={o.x2} y2={o.y2} stroke="currentColor" strokeWidth={o.type==='stitch'?'.45':'.8'} strokeDasharray={o.type==='stitch'?'2 1':undefined}/>) }
  {drag&&<line x1={drag.start.x} y1={drag.start.y} x2={drag.current.x} y2={drag.current.y} stroke="currentColor" strokeWidth=".7" strokeDasharray="2 1"/>}
 </svg>
 {selected&&<button className="tt-delete-selected" onClick={()=>remove(selected)}><Trash2 size={14}/> Delete selected</button>}
 </div>
}

export default function TailorTools({setPage}){
 const toast=useToast(); const [boards,setBoards]=useState([]),[board,setBoard]=useState(null),[ops,setOps]=useState(DEFAULT_OPS),[tool,setTool]=useState('select'),[selected,setSelected]=useState(null),[projects,setProjects]=useState([]),[projectId,setProjectId]=useState(''),[ai,setAi]=useState(null),[request,setRequest]=useState('Check the construction, seam placement, allowances and stitch sequence for this pattern.'),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[unit,setUnit]=useState('cm');
 useEffect(()=>{Promise.allSettled([api('/api/tailor-tools/boards'),api('/api/workspace-suite/projects?limit=50')]).then(([b,p])=>{if(b.status==='fulfilled'){setBoards(b.value.boards||[]);if(b.value.boards?.[0]){setBoard(b.value.boards[0]);setOps(b.value.boards[0].operations?.length?b.value.boards[0].operations:DEFAULT_OPS);setUnit(b.value.boards[0].unit||'cm')}}if(p.status==='fulfilled')setProjects(p.value.projects||[])})},[]);
 const create=async()=>{try{const d=await api('/api/tailor-tools/boards',{method:'POST',body:JSON.stringify({name:'Tailor Board',projectId:projectId||null,unit})});setBoard(d.board);setBoards(b=>[d.board,...b]);setOps(DEFAULT_OPS);toast.success('Tailor board created.')}catch(e){toast.error(e.message)}};
 const save=async()=>{if(!board)return create();setSaving(true);try{const d=await api(`/api/tailor-tools/boards/${board.id}`,{method:'PUT',body:JSON.stringify({operations:ops,projectId:projectId||board.projectId||null,unit,aiContext:ai||{}})});setBoard(d.board);setBoards(bs=>bs.map(x=>x.id===d.board.id?d.board:x));toast.success('Tailor board saved.')}catch(e){toast.error(e.message)}finally{setSaving(false)}};
 const ask=async()=>{setBusy(true);try{const p=projects.find(x=>x.id===projectId)||null;const d=await api('/api/tailor-tools/ai',{method:'POST',body:JSON.stringify({request,project:p,board:{...board,operations:ops},measurements:p?.measurements||{},fabric:p?.fabric||''})});setAi(d);toast.success('AI analysis ready. Review suggestions before applying.')}catch(e){toast.error(e.message)}finally{setBusy(false)}};
 const applySuggestion=s=>{if(!s?.operations?.length)return;const mapped=s.operations.map(o=>({...o,id:uid()}));setOps(o=>[...o,...mapped]);toast.success('AI suggestion added to the board.');};
 const removeSelected=()=>{if(!selected)return;setOps(o=>o.filter(x=>x.id!==selected));setSelected(null)};
 const selectedOp=ops.find(o=>o.id===selected);
 const currentProject=projects.find(x=>x.id===projectId);
 return <div className="tt-page">
  <header className="tt-hero"><div><span className="tt-eyebrow"><Scissors size={13}/> TAILOR TOOLS</span><h2>Draw, measure and build the garment correctly.</h2><p>A structured pattern board for seam lines, allowances, notches, darts, grainlines, stitch plans and cutting preparation — with Gemini guidance before you apply changes.</p></div><div className="tt-actions"><button className="btn btn-ghost" onClick={create}><Plus size={15}/> New board</button><button className="btn btn-primary" onClick={save} disabled={saving}>{saving?<Sparkles size={15}/>:<Save size={15}/>} {saving?'Saving':'Save'}</button>{board&&<button className="btn btn-ghost" onClick={()=>downloadFile(`${API}/api/tailor-tools/boards/${board.id}/export.svg`,`${(board.name||'tailor-board').replace(/\s+/g,'-')}.svg`)}><Download size={15}/> Export SVG</button>}</div></header>
  <div className="tt-toolbar"><div className="tt-tools">{TOOLS.map(([id,label,Icon])=><button key={id} className={tool===id?'active':''} title={label} onClick={()=>setTool(id)}><Icon size={16}/><span>{label}</span></button>)}</div><div className="tt-meta"><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project linked</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="cm">cm</option><option value="mm">mm</option><option value="in">in</option></select></div></div>
  <div className="tt-grid"><section className="tt-card tt-canvas"><div className="tt-card-head"><div><strong>{board?.name||'Tailor board'}</strong><small>{currentProject?`Linked to ${currentProject.name}`:'Unsaved working board'} · {ops.length} operations</small></div><button className="btn btn-ghost btn-sm" onClick={()=>setOps(DEFAULT_OPS)}><Eraser size={14}/> Reset board</button></div><Board ops={ops} tool={tool} onChange={setOps} selected={selected} setSelected={setSelected}/></section>
  <aside className="tt-side"><section className="tt-card"><div className="tt-card-head"><div><strong>AI Tailor</strong><small>Gemini checks construction and suggests changes.</small></div><Bot size={19}/></div><textarea value={request} onChange={e=>setRequest(e.target.value)} rows={4} placeholder="Ask about seam placement, darts, fit, cutting or stitch order…"/><button className="btn btn-primary tt-ai-btn" onClick={ask} disabled={busy}><Wand2 size={15}/>{busy?'Analyzing…':'Ask AI'}</button>{ai&&<div className="tt-ai-result"><div className="tt-confidence"><span>Detected garment</span><b>{ai.garment_type||'Not confirmed'}</b><em>{Math.round((Number(ai.confidence)||0)*100)}% confidence</em></div><p>{ai.summary}</p>{ai.warnings?.length>0&&<div className="tt-warnings">{ai.warnings.map((w,i)=><div key={i}>• {w}</div>)}</div>}{ai.suggestions?.map((s,i)=><div className="tt-suggestion" key={i}><strong>{s.title}</strong><p>{s.reason}</p><button className="btn btn-ghost btn-sm" onClick={()=>applySuggestion(s)}><Check size={13}/> Apply to board</button></div>)}</div>}</section>
  <section className="tt-card"><div className="tt-card-head"><div><strong>Selected operation</strong><small>Use the board to place construction marks.</small></div></div>{selectedOp?<dl className="tt-detail"><div><dt>Type</dt><dd>{selectedOp.type}</dd></div>{selectedOp.allowance!==undefined&&<div><dt>Allowance</dt><dd>{selectedOp.allowance} {unit}</dd></div>}{selectedOp.name&&<div><dt>Piece</dt><dd>{selectedOp.name}</dd></div>}</dl>:<p className="tt-empty">Select a pattern piece or mark to inspect it.</p>}<button className="btn btn-ghost btn-sm tt-danger" disabled={!selected} onClick={removeSelected}><Trash2 size={13}/> Delete selected</button></section>
  <section className="tt-card"><div className="tt-card-head"><div><strong>Construction checklist</strong><small>Before cutting</small></div></div><ul className="tt-checks"><li><Check size={13}/> Grainline is defined</li><li><Check size={13}/> Seam allowances are checked</li><li><Check size={13}/> Notches match joining pieces</li><li><Check size={13}/> Measurements are verified</li><li><Check size={13}/> Stitch order is documented</li></ul></section>
  </aside></div>
 </div>
}
