import React, { useEffect, useRef, useState } from 'react';
import { LogOut, Menu, X, Plus, ChevronDown, Settings, PanelLeftClose, PanelLeftOpen, Search, LayoutDashboard, Scissors, FolderKanban, Layers } from 'lucide-react';
import { Brand } from './Logo.jsx';
import { NAV_GROUPS, NAV } from '../nav.js';

function initials(name=''){const p=name.trim().split(/\s+/).filter(Boolean);return ((p[0]?.[0]||'U')+(p[1]?.[0]||'')).toUpperCase()}

export function Sidebar({page,setPage,open,close,user,usage,collapsed,onToggle}){
 const pct=Math.min(100,(usage.used/Math.max(1,usage.limit))*100);
 return <><div className={`scrim ${open?'show':''}`} onClick={close}/><aside className={`sidebar ${open?'open':''} ${collapsed?'collapsed':''}`} aria-label="Primary">
   <div className="side-top"><Brand light/><button className="icon-btn side-collapse" onClick={onToggle} aria-label={collapsed?'Expand sidebar':'Collapse sidebar'}>{collapsed?<PanelLeftOpen size={20}/>:<PanelLeftClose size={20}/>}</button><button className="icon-btn side-close" onClick={close} aria-label="Close menu"><X size={20}/></button></div>
   <nav className="side-nav">{NAV_GROUPS.map(g=><div className="nav-group" key={g.label}><div className="nav-label">{g.label}</div>{g.items.map(({id,label,icon:Icon})=><button key={id} className={`nav-item ${page===id?'active':''}`} aria-current={page===id?'page':undefined} title={collapsed?label:undefined} onClick={()=>{setPage(id);close()}}><Icon size={18}/><span>{label}</span></button>)}</div>)}</nav>
   <button className="side-meter" title={collapsed?'Usage':undefined} onClick={()=>{setPage('usage');close()}}><div className="meter-head"><span>Images this month</span><strong>{usage.used.toLocaleString()} / {usage.limit.toLocaleString()}</strong></div><div className="meter"><i style={{width:`${pct}%`}}/></div></button>
 </aside></>
}

function HealthPill({health}){if(!health||health==='ok')return health==='ok'?<span className="health ok hide-sm" title="Pattern engine online"><i/>Engine online</span>:null;return <span className="health bad" role="status"><i/>{health==='engine'?'Pattern engine offline':'Can\'t reach the API'}</span>}

export function BottomNav({page,setPage,openMenu}){const items=[{id:'overview',label:'Home',icon:LayoutDashboard},{id:'studio',label:'Studio',icon:Scissors},{id:'fashion-command',label:'Fashion OS',icon:Layers},{id:'projects',label:'Projects',icon:FolderKanban}];const isOn=id=>id==='fashion-command'?page.startsWith('fashion-'):page===id;return <nav className="bottom-nav" aria-label="Quick navigation">{items.map(({id,label,icon:Icon})=><button key={id} data-no-spin className={isOn(id)?'on':''} aria-current={isOn(id)?'page':undefined} onClick={()=>setPage(id)}><Icon size={20}/><span>{label}</span></button>)}<button data-no-spin onClick={openMenu}><Menu size={20}/><span>More</span></button></nav>}

export function Topbar({page,setPage,openMenu,user,onLogout,onSearch,health}){const [menu,setMenu]=useState(false);const ref=useRef(null);const current=NAV.find(n=>n.id===page);useEffect(()=>{const onDoc=e=>{if(ref.current&&!ref.current.contains(e.target))setMenu(false)};const onKey=e=>{if(e.key==='Escape')setMenu(false)};document.addEventListener('mousedown',onDoc);document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('mousedown',onDoc);document.removeEventListener('keydown',onKey)}},[]);return <header className="topbar"><button className="icon-btn menu-btn" onClick={openMenu} aria-label="Open menu"><Menu size={22}/></button><div className="top-title" key={page}><h1>{current?.label}</h1><p>{current?.sub}</p></div><div className="top-actions">{page!=='studio'&&page!=='assistant'&&<button className="btn btn-primary" aria-label="New product" onClick={()=>setPage('fashion-capture')}><Plus size={16}/><span className="hide-sm">New product</span></button>}<HealthPill health={health}/><button className="search-pill hide-sm" data-no-spin onClick={onSearch} aria-label="Open command palette"><Search size={15}/><span>Search</span><kbd>Ctrl K</kbd></button><button className="icon-btn top-icon show-sm" data-no-spin onClick={onSearch} aria-label="Search"><Search size={19}/></button><div className="user-menu" ref={ref}><button className="user-btn" onClick={()=>setMenu(m=>!m)} aria-haspopup="menu" aria-expanded={menu}><span className="avatar">{initials(user.name)}</span><span className="user-meta hide-sm"><strong>{user.name}</strong><small>{user.email}</small></span><ChevronDown size={16} className="hide-sm"/></button>{menu&&<div className="menu-pop" role="menu"><div className="menu-id"><strong>{user.name}</strong><small>{user.email}</small></div><button role="menuitem" onClick={()=>{setPage('settings');setMenu(false)}}><Settings size={16}/> Settings</button><button role="menuitem" onClick={onLogout}><LogOut size={16}/> Sign out</button></div>}</div></div></header>}
